import Foundation
@testable import OffRentDomain

// Regenerates the documents that must not drift from the code.
//
//   swift run offrent-docgen <repo-root>
//
// CI runs it with `--check`, which regenerates into memory and fails if the committed file
// differs. A status transition table that disagrees with the state machine is worse than no
// table, because a reviewer will believe it.

let arguments = CommandLine.arguments
let checkOnly = arguments.contains("--check")
let root = arguments.dropFirst().first { !$0.hasPrefix("--") } ?? FileManager.default.currentDirectoryPath

func statusTransitionMarkdown() -> String {
    var lines = [
        "# Status transitions",
        "",
        "**Generated by `swift run offrent-docgen`. Do not edit by hand.**",
        "",
        "Source: `StatusTransitionService.allowedTransitions` and `.reopenTargets`.",
        "`OffRentDomainTests/StatusTransitionDocTests` fails if this file and the code disagree.",
        "",
        "## Forward transitions",
        "",
        "| From | May move to | Notes |",
        "| --- | --- | --- |",
    ]

    for status in RentalItemStatus.allCases.sorted(by: { $0.order < $1.order }) {
        let destinations = (StatusTransitionService.allowedTransitions[status] ?? [])
            .sorted { $0.order < $1.order }
            .map(\.displayName)
        let destinationText = destinations.isEmpty ? "_terminal_" : destinations.joined(separator: ", ")
        lines.append("| \(status.displayName) | \(destinationText) | \(status.explanation) |")
    }

    let reopenList = StatusTransitionService.reopenTargets
        .sorted { $0.order < $1.order }
        .map { "`\($0.displayName)`" }
        .joined(separator: ", ")

    lines += [
        "",
        "## Reopening",
        "",
        "Reopening bypasses the table above. It requires a non-empty reason, writes a `reopened`",
        "event, and may only move an item *backwards* — the target's order must be lower than the",
        "current status's.",
        "",
        "Reopen targets: " + reopenList + ".",
        "",
        "`Draft` is deliberately not a reopen target: a rental that happened cannot un-happen, and",
        "the timeline would then contradict itself.",
        "",
        "## Properties enforced by tests",
        "",
        "- No intent reaches `Confirmation Recorded` from any status other than `Contact Vendor`.",
        "- `Contact Vendor` → `Confirmation Recorded` additionally requires the user to affirm they",
        "  contacted the vendor, and either a confirmation number or an explicit acknowledgement",
        "  that the vendor gave none.",
        "- Every edge in the table is reachable by some intent, and no intent produces an edge that",
        "  is not in the table (reopen excepted).",
        "- `Resolved` and `Archived` are the only statuses that stop counting against the free-tier",
        "  open-item limit.",
        "- `Active` and `Contact Vendor` are the only statuses that accrue an estimate.",
        "",
    ]
    return lines.joined(separator: "\n")
}

let targets: [(path: String, contents: String)] = [
    ("docs/STATUS_TRANSITIONS.md", statusTransitionMarkdown())
]

var failed = false
for target in targets {
    let url = URL(fileURLWithPath: root).appendingPathComponent(target.path)
    let existing = try? String(contentsOf: url, encoding: .utf8)
    if checkOnly {
        if existing != target.contents {
            FileHandle.standardError.write(Data("STALE: \(target.path) — run `swift run offrent-docgen`\n".utf8))
            failed = true
        } else {
            print("ok: \(target.path)")
        }
    } else {
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true
        )
        try target.contents.write(to: url, atomically: true, encoding: .utf8)
        print("wrote: \(target.path)")
    }
}
if failed { exit(1) }
