import Foundation

/// The assembled contents of an evidence packet, as pure data.
///
/// The PDF renderer draws this and nothing else. Splitting them means the packet's *contents* —
/// which is what a user might one day put in front of a rental company — are asserted in tests
/// that run without PDFKit, while the renderer is left with only layout to get wrong.
struct EvidencePacket: Sendable, Equatable {

    struct PartySummary: Sendable, Equatable {
        var name: String
        var branch: String?
        var phone: String?
        var email: String?
        var link: String?
    }

    struct SiteSummary: Sendable, Equatable {
        var name: String
        var projectIdentifier: String?
        var address: String?
    }

    struct TimelineEntry: Sendable, Equatable {
        var timestamp: Date
        var title: String
        var detail: String?
        var contactMethod: VendorContactMethod?
        var vendorRepresentative: String?
        var confirmationNumber: String?
        var hasLocation: Bool
    }

    struct AssetSummary: Sendable, Equatable {
        var displayName: String
        var caption: String?
        var capturedAt: Date
        var mediaType: EvidenceMediaType
        var relativePath: String
        var sha256: String?
        var hasCoordinate: Bool
    }

    var generatedAt: Date
    var appDisplayName: String
    var appVersion: String
    var companyName: String

    var vendor: PartySummary
    var jobSite: SiteSummary?
    var agreementNumber: String?
    var agreementStartDate: Date
    var agreementScheduledEndDate: Date?

    var equipmentName: String
    var equipmentClass: String?
    var vendorEquipmentIdentifier: String?
    var serialNumber: String?
    var status: RentalItemStatus

    var terms: RentalTerms
    var estimate: RunningEstimate

    var timeline: [TimelineEntry]
    var confirmation: ConfirmationEvidence?
    var pickup: PickupEvidence?
    var meterUnit: MeterUnit

    var selectedAssets: [AssetSummary]

    var invoice: InvoiceValue?
    var comparison: InvoiceComparison?

    var userNotes: String?
    var disclaimer: String

    /// Contact attempts, pulled out of the timeline for their own section: the number of times
    /// somebody tried to reach the yard is the part a reader scans for.
    var contactAttempts: [TimelineEntry] {
        timeline.filter { $0.contactMethod != nil }
    }
}

enum EvidencePacketBuilder {

    /// The disclaimer that appears on the packet.
    ///
    /// Written to be readable rather than to be long. Every sentence here corresponds to a claim
    /// the app must not make, and the document is worse than useless if a reader takes it for
    /// something it is not.
    static func disclaimer(appName: String, companyName: String) -> String {
        """
        About this document

        This packet was assembled by \(appName) from information its user entered or captured. \
        It is a record of what that user recorded, and when.

        • Amounts shown as estimates are calculated from rates and dates the user confirmed. They \
        are estimates, not invoices, and not a statement of what is owed.
        • \(appName) did not contact the rental company and did not end any rental. Any \
        confirmation number shown here was entered by the user after they contacted the vendor \
        themselves.
        • Timestamps record when information was entered into \(appName) on the user's device. \
        They are not independently witnessed and are not legally binding.
        • Any text read from a scanned document may be misread. Every value in this packet was \
        reviewed and accepted by the user, but the underlying document controls.
        • File checksums are included as an integrity aid so a reader can tell whether an \
        attachment has changed. They are not a chain of custody and prove nothing about origin.
        • A "possible mismatch" means the invoice differs from terms the user confirmed. It is \
        not a determination that any charge is incorrect, unauthorised or unlawful.
        • The rental company's own agreement governs the rental. \(appName) does not provide \
        legal, accounting, insurance or contract advice.

        Generated by \(appName). \(companyName).
        """
    }

    /// A per-item summary line for the packet header and for share sheets.
    static func headline(for packet: EvidencePacket) -> String {
        var parts = [packet.equipmentName]
        if let identifier = packet.vendorEquipmentIdentifier { parts.append("(\(identifier))") }
        parts.append("—")
        parts.append(packet.vendor.name)
        if let number = packet.agreementNumber { parts.append("· \(number)") }
        return parts.joined(separator: " ")
    }

    /// Whether a packet is worth generating.
    ///
    /// A packet with nothing in it but a name is a document that makes the app look thorough and
    /// helps nobody, so the export button explains what is missing instead.
    static func completeness(of packet: EvidencePacket) -> [String] {
        var missing: [String] = []
        if packet.confirmation == nil { missing.append("No vendor confirmation is recorded.") }
        if packet.confirmation?.trimmedConfirmationNumber == nil,
           packet.confirmation != nil {
            missing.append("No confirmation number was captured.")
        }
        if packet.pickup == nil { missing.append("No pickup is recorded.") }
        if packet.selectedAssets.isEmpty { missing.append("No photos or documents are attached.") }
        if packet.invoice == nil { missing.append("No final invoice is attached.") }
        if !packet.estimate.isComplete {
            missing.append("The rent estimate is incomplete: \(packet.estimate.blockingIssue?.message ?? "rates are missing").")
        }
        return missing
    }
}
